# Generated by Django 5.2.17 on 2026-10-04 17:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=100, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('client_or_unit', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('scope', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('objectives', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_review', 'In review'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('methodology', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('executive_summary', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='engagement_period_order'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'in_review', 'completed'])), name='engagement_state')],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('risks_addressed', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('framework_references', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('testing_procedure', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retirement_reason', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.UUIDField()),
                ('entity_code', models.CharField(max_length=40)),
                ('operation', models.CharField(max_length=40)),
                ('actor_label', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('owner', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('ready_for_verification', 'Ready for verification'), ('completed', 'Completed')], default='not_started', max_length=25)),
                ('blocked_reason', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('closure_verifier', models.CharField(blank=True, max_length=200)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('closure_conclusion', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('type', models.CharField(choices=[('url', 'Url'), ('document_path', 'Document path'), ('external_document_id', 'External document id')], max_length=25)),
                ('source', models.CharField(max_length=2048)),
                ('source_system', models.CharField(blank=True, max_length=200)),
                ('collection_date', models.DateField()),
                ('owner', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='unreviewed', max_length=15)),
                ('reviewer', models.CharField(blank=True, max_length=200)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('rejection_reason', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.action')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='ActionClosureEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.action')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.evidence')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='closure_evidence',
            field=models.ManyToManyField(blank=True, related_name='closed_actions', through='ledger.ActionClosureEvidence', to='ledger.evidence'),
        ),
        migrations.AddField(
            model_name='action',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='actions', through='ledger.ActionEvidence', to='ledger.evidence'),
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('condition', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('criteria', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('cause', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('impact', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], default='medium', max_length=15)),
                ('severity_rationale', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('recommendation', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('resolved', 'Resolved'), ('withdrawn', 'Withdrawn')], default='draft', max_length=15)),
                ('resolution_verifier', models.CharField(blank=True, max_length=200)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('resolution_conclusion', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('withdrawal_reason', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='action',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='ledger.finding'),
        ),
        migrations.CreateModel(
            name='FindingClosureEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.evidence')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.finding')),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='closure_evidence',
            field=models.ManyToManyField(blank=True, related_name='closed_findings', through='ledger.FindingClosureEvidence', to='ledger.evidence'),
        ),
        migrations.CreateModel(
            name='FindingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.control')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.finding')),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='findings', through='ledger.FindingControl', to='ledger.control'),
        ),
        migrations.CreateModel(
            name='FindingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.evidence')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.finding')),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='findings', through='ledger.FindingEvidence', to='ledger.evidence'),
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_updates', to='ledger.action')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(max_length=40)),
                ('procedure_snapshot', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('tester', models.CharField(blank=True, max_length=200)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('sample_description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('work_performed', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('effective', 'Effective'), ('partially_effective', 'Partially effective'), ('ineffective', 'Ineffective'), ('not_applicable', 'Not applicable'), ('unable_to_conclude', 'Unable to conclude')], max_length=25)),
                ('conclusion', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('applicability_or_limitation_rationale', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('no_finding_rationale', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.control')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FindingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.finding')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.test')),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='findings', through='ledger.FindingTest', to='ledger.test'),
        ),
        migrations.CreateModel(
            name='TestEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.engagement')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.evidence')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='tests', through='ledger.TestEvidence', to='ledger.evidence'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(fields=('engagement', 'code'), name='control_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('engagement', 'code'), name='evidence_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['url', 'document_path', 'external_document_id'])), name='evidence_type'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['unreviewed', 'reviewed', 'rejected'])), name='evidence_state'),
        ),
        migrations.AddConstraint(
            model_name='actionevidence',
            constraint=models.UniqueConstraint(fields=('action', 'evidence'), name='unique_action_support'),
        ),
        migrations.AddConstraint(
            model_name='actionclosureevidence',
            constraint=models.UniqueConstraint(fields=('action', 'evidence'), name='unique_action_closure'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('engagement', 'code'), name='action_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['not_started', 'in_progress', 'blocked', 'ready_for_verification', 'completed'])), name='action_state'),
        ),
        migrations.AddConstraint(
            model_name='findingclosureevidence',
            constraint=models.UniqueConstraint(fields=('finding', 'evidence'), name='unique_finding_closure'),
        ),
        migrations.AddConstraint(
            model_name='findingcontrol',
            constraint=models.UniqueConstraint(fields=('finding', 'control'), name='unique_finding_control'),
        ),
        migrations.AddConstraint(
            model_name='findingevidence',
            constraint=models.UniqueConstraint(fields=('finding', 'evidence'), name='unique_finding_evidence'),
        ),
        migrations.AddConstraint(
            model_name='findingtest',
            constraint=models.UniqueConstraint(fields=('finding', 'test'), name='unique_finding_test'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('engagement', 'code'), name='finding_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'open', 'resolved', 'withdrawn'])), name='finding_state'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['critical', 'high', 'medium', 'low', 'informational'])), name='finding_severity'),
        ),
        migrations.AddConstraint(
            model_name='testevidence',
            constraint=models.UniqueConstraint(fields=('test', 'evidence'), name='unique_test_evidence'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('engagement', 'code'), name='test_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'in_progress', 'completed'])), name='test_state'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ['', 'effective', 'partially_effective', 'ineffective', 'not_applicable', 'unable_to_conclude'])), name='test_result'),
        ),
    ]
