# Generated by Django 5.2.17 on 2026-10-05 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_engagement_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], max_length=10)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ledger.engagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('engagement', 'user'), name='unique_engagement_member'), models.CheckConstraint(condition=models.Q(('role__in', ['viewer', 'editor'])), name='membership_role')],
            },
        ),
    ]
